version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: crescebr_db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-crescebr_dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - crescebr-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: crescebr_backend
    depends_on:
      - postgres
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - crescebr-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: crescebr_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
    networks:
      - crescebr-net

networks:
  crescebr-net:
    driver: bridge

volumes:
  postgres_data:
