version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crescebr_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crescebr-net

  backend:
    container_name: crescebr_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app/backend
      - ./shared:/usr/src/app/shared
      - /usr/src/app/backend/node_modules
    networks:
      - crescebr-net

  frontend:
    container_name: crescebr_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '8080:80' # Access the app at http://localhost:8080
    depends_on:
      - backend
    networks:
      - crescebr-net

networks:
  crescebr-net:
    driver: bridge

volumes:
  postgres_data:
