version: '3.8'

services:
  db:
    image: postgres:13
    container_name: crescebr_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: crescebr_backend
    command: npm run dev
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://testuser:testpass@db:5432/testdb
      TEST_DATABASE_URL: postgres://testuser:testpass@db:5432/testdb
      JWT_SECRET: your_jwt_secret
      PORT: 3001
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: crescebr_frontend
    command: npm run dev
    ports:
      - '5173:5173' # Changed port for clarity
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
