/**
 * Catalog and company fixtures for the browser-side demo API.
 *
 * Generated from `backend/seeders/20240101000001-initial-data.cjs` so the
 * hosted demo shows exactly the data a real deployment would seed. Regenerate
 * with `npm run demo:data` after changing the seeder; do not hand-edit.
 */

import type { Company, Product } from '@shared/types';

/** Sign-in fixtures. Public on purpose — the same values ship in the seeder. */
export const DEMO_PASSWORDS: Record<string, string> = {
  'admin@crescebr.com': 'admin123',
  'supplier@example.com': 'supplier123',
  'supplier2@example.com': 'supplier123',
  'supplier3@example.com': 'supplier123',
  'supplier4@example.com': 'supplier123',
  'buyer@example.com': 'buyer123',
};

export const SEED_COMPANIES: Company[] = [
  {
    id: 1,
    email: 'admin@crescebr.com',
    cpf: '123.456.789-00',
    address: 'Rua Principal, 123, Cascavel, PR',
    role: 'admin',
    status: 'approved',
    companyName: 'CresceBR Admin',
    corporateName: 'CresceBR Administracao LTDA',
    cnpj: '00.000.000/0001-00',
    cnpjValidated: false,
    industrySector: 'other',
    companyType: 'both',
  },
  {
    id: 2,
    email: 'supplier@example.com',
    cpf: '111.222.333-44',
    address: 'Av. Industrial, 500, Curitiba, PR',
    role: 'supplier',
    status: 'approved',
    companyName: 'Industrial Solutions',
    corporateName: 'Industrial Solutions LTDA',
    cnpj: '22.222.222/0001-22',
    cnpjValidated: false,
    industrySector: 'machinery',
    companyType: 'supplier',
  },
  {
    id: 3,
    email: 'buyer@example.com',
    cpf: '555.666.777-88',
    address: 'Av. Brasil, 456, Foz do Iguacu, PR',
    role: 'customer',
    status: 'approved',
    companyName: 'Buyer Corp',
    corporateName: 'Buyer Corp Comercio LTDA',
    cnpj: '33.333.333/0001-33',
    cnpjValidated: false,
    industrySector: 'construction',
    companyType: 'buyer',
  },
  {
    id: 4,
    email: 'supplier2@example.com',
    cpf: '222.333.444-55',
    address: 'Rua da Tecnologia, 1200, Londrina, PR',
    role: 'supplier',
    status: 'approved',
    companyName: 'Apex Electronics Supply',
    corporateName: 'Apex Electronics Supply LTDA',
    cnpj: '44.444.444/0001-44',
    cnpjValidated: false,
    industrySector: 'electronics',
    companyType: 'supplier',
  },
  {
    id: 5,
    email: 'supplier3@example.com',
    cpf: '333.444.555-66',
    address: 'Rod. do Cimento, 3000, Ponta Grossa, PR',
    role: 'supplier',
    status: 'approved',
    companyName: 'BuildPro Materials',
    corporateName: 'BuildPro Materials LTDA',
    cnpj: '55.555.555/0001-55',
    cnpjValidated: false,
    industrySector: 'construction',
    companyType: 'supplier',
  },
  {
    id: 6,
    email: 'supplier4@example.com',
    cpf: '444.555.666-77',
    address: 'Av. das Industrias Quimicas, 850, Araucaria, PR',
    role: 'supplier',
    status: 'approved',
    companyName: 'ChemSource Industrial',
    corporateName: 'ChemSource Industrial SA',
    cnpj: '66.666.666/0001-66',
    cnpjValidated: false,
    industrySector: 'chemicals',
    companyType: 'supplier',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Industrial Bearing XYZ-500',
    description:
      'High-precision ball bearing for industrial machinery. Grade ABEC-7, suitable for heavy-duty applications.',
    price: 150,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    category: 'Components',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [
      { minQuantity: 1, maxQuantity: 50, discount: 0 },
      { minQuantity: 51, maxQuantity: 200, discount: 0.1 },
      { minQuantity: 201, maxQuantity: null, discount: 0.2 },
    ],
    specifications: { size: '50mm', material: 'Steel', grade: 'ABEC-7' },
    unitPrice: 150,
    minimumOrderQuantity: 10,
    leadTime: 5,
    availability: 'in_stock',
  },
  {
    id: 2,
    name: 'Professional Hydraulic Press',
    description:
      'Heavy-duty hydraulic press with 50-ton capacity. Digital pressure gauge included.',
    price: 15000,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Hydraulic_press.jpg/960px-Hydraulic_press.jpg',
    category: 'Machinery',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [],
    specifications: { capacity: '50 tons', power: '380V', weight: '2500kg' },
    unitPrice: 15000,
    minimumOrderQuantity: 1,
    leadTime: 14,
    availability: 'in_stock',
  },
  {
    id: 3,
    name: 'Premium Construction Steel Rebar',
    description: 'CA-50 steel rebar, 12mm diameter, compliant with NBR 7480. Sold per ton.',
    price: 4200,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
    category: 'Construction',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [
      { minQuantity: 1, maxQuantity: 5, discount: 0 },
      { minQuantity: 6, maxQuantity: 20, discount: 0.05 },
      { minQuantity: 21, maxQuantity: null, discount: 0.12 },
    ],
    specifications: { diameter: '12mm', standard: 'NBR 7480', type: 'CA-50' },
    unitPrice: 4200,
    minimumOrderQuantity: 1,
    leadTime: 7,
    availability: 'in_stock',
  },
  {
    id: 4,
    name: 'Industrial Automation PLC Module',
    description:
      'Programmable Logic Controller module with 16 digital I/O. Modbus and Ethernet support.',
    price: 2800,
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837',
    category: 'Electronics',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [
      { minQuantity: 1, maxQuantity: 10, discount: 0 },
      { minQuantity: 11, maxQuantity: 50, discount: 0.08 },
      { minQuantity: 51, maxQuantity: null, discount: 0.15 },
    ],
    specifications: { io_count: '16', protocols: 'Modbus, Ethernet', voltage: '24V DC' },
    unitPrice: 2800,
    minimumOrderQuantity: 1,
    leadTime: 10,
    availability: 'in_stock',
  },
  {
    id: 5,
    name: 'Safety Helmet - Industrial Grade',
    description: 'ANSI Z89.1 compliant industrial safety helmet with adjustable suspension.',
    price: 45,
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Ameriza-entilated_safety_helmet.jpg/960px-Ameriza-entilated_safety_helmet.jpg',
    category: 'Safety',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [
      { minQuantity: 20, maxQuantity: 100, discount: 0 },
      { minQuantity: 101, maxQuantity: 500, discount: 0.1 },
      { minQuantity: 501, maxQuantity: null, discount: 0.18 },
    ],
    specifications: { standard: 'ANSI Z89.1', material: 'HDPE', color: 'Yellow' },
    unitPrice: 45,
    minimumOrderQuantity: 20,
    leadTime: 3,
    availability: 'in_stock',
  },
  {
    id: 6,
    name: 'Industrial Air Compressor 100L',
    description:
      'Belt-driven 100L air compressor, 8 bar working pressure, 3 HP motor for workshop and assembly lines.',
    price: 8900,
    imageUrl: 'https://images.unsplash.com/photo-1567789884554-0b844b597180',
    category: 'Machinery',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [
      { minQuantity: 1, maxQuantity: 5, discount: 0 },
      { minQuantity: 6, maxQuantity: null, discount: 0.07 },
    ],
    specifications: { capacity: '100L', pressure: '8 bar', power: '3HP' },
    unitPrice: 8900,
    minimumOrderQuantity: 1,
    leadTime: 12,
    availability: 'in_stock',
  },
  {
    id: 7,
    name: 'CNC Spindle Motor 2.2kW',
    description:
      'Air-cooled high-frequency spindle motor for CNC routers. 24,000 RPM, ER20 collet.',
    price: 3200,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    category: 'Machinery',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [],
    specifications: { power: '2.2kW', rpm: '24000', cooling: 'Air' },
    unitPrice: 3200,
    minimumOrderQuantity: 2,
    leadTime: 9,
    availability: 'limited',
  },
  {
    id: 8,
    name: 'Stainless Steel Conveyor Belt 5m',
    description:
      'Food-grade AISI 304 stainless steel modular conveyor belt, 600mm width, 5m length.',
    price: 6750,
    imageUrl: 'https://images.unsplash.com/photo-1567789884554-0b844b597180',
    category: 'Machinery',
    supplierId: 2,
    supplier: {
      id: 2,
      companyName: 'Industrial Solutions',
      corporateName: 'Industrial Solutions LTDA',
    },
    tierPricing: [],
    specifications: { length: '5m', material: 'AISI 304', width: '600mm' },
    unitPrice: 6750,
    minimumOrderQuantity: 1,
    leadTime: 15,
    availability: 'custom_order',
  },
  {
    id: 9,
    name: 'Three-Phase Induction Motor 5HP',
    description: 'TEFC three-phase induction motor, 5 HP, 380V, 4-pole, IE3 efficiency class.',
    price: 1850,
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837',
    category: 'Electronics',
    supplierId: 4,
    supplier: {
      id: 4,
      companyName: 'Apex Electronics Supply',
      corporateName: 'Apex Electronics Supply LTDA',
    },
    tierPricing: [
      { minQuantity: 1, maxQuantity: 10, discount: 0 },
      { minQuantity: 11, maxQuantity: null, discount: 0.1 },
    ],
    specifications: { power: '5HP', voltage: '380V', poles: '4' },
    unitPrice: 1850,
    minimumOrderQuantity: 2,
    leadTime: 7,
    availability: 'in_stock',
  },
  {
    id: 10,
    name: 'Industrial Ethernet Switch 8-Port',
    description:
      'DIN-rail managed industrial Ethernet switch, 8x Gigabit ports, -40C to 75C operating range.',
    price: 980,
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837',
    category: 'Electronics',
    supplierId: 4,
    supplier: {
      id: 4,
      companyName: 'Apex Electronics Supply',
      corporateName: 'Apex Electronics Supply LTDA',
    },
    tierPricing: [
      { minQuantity: 5, maxQuantity: 50, discount: 0 },
      { minQuantity: 51, maxQuantity: null, discount: 0.12 },
    ],
    specifications: { ports: '8', speed: '1Gbps', mounting: 'DIN rail' },
    unitPrice: 980,
    minimumOrderQuantity: 5,
    leadTime: 6,
    availability: 'in_stock',
  },
  {
    id: 11,
    name: 'Variable Frequency Drive 7.5kW',
    description: 'Vector-control VFD, 7.5kW, 380V input, Modbus RTU, built-in EMC filter.',
    price: 2450,
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837',
    category: 'Electronics',
    supplierId: 4,
    supplier: {
      id: 4,
      companyName: 'Apex Electronics Supply',
      corporateName: 'Apex Electronics Supply LTDA',
    },
    tierPricing: [],
    specifications: { power: '7.5kW', input: '380V', protocol: 'Modbus' },
    unitPrice: 2450,
    minimumOrderQuantity: 1,
    leadTime: 10,
    availability: 'in_stock',
  },
  {
    id: 12,
    name: 'Capacitive Proximity Sensor M18',
    description:
      'M18 capacitive proximity sensor, 8mm sensing range, PNP normally-open output, IP67.',
    price: 145,
    imageUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837',
    category: 'Electronics',
    supplierId: 4,
    supplier: {
      id: 4,
      companyName: 'Apex Electronics Supply',
      corporateName: 'Apex Electronics Supply LTDA',
    },
    tierPricing: [
      { minQuantity: 10, maxQuantity: 100, discount: 0 },
      { minQuantity: 101, maxQuantity: null, discount: 0.15 },
    ],
    specifications: { range: '8mm', output: 'PNP', housing: 'M18' },
    unitPrice: 145,
    minimumOrderQuantity: 10,
    leadTime: 4,
    availability: 'in_stock',
  },
  {
    id: 13,
    name: 'Portland Cement CP-II (per ton)',
    description: 'CP-II-E-32 Portland cement compliant with NBR 11578. Sold per metric ton.',
    price: 580,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
    category: 'Construction',
    supplierId: 5,
    supplier: {
      id: 5,
      companyName: 'BuildPro Materials',
      corporateName: 'BuildPro Materials LTDA',
    },
    tierPricing: [
      { minQuantity: 5, maxQuantity: 20, discount: 0 },
      { minQuantity: 21, maxQuantity: null, discount: 0.08 },
    ],
    specifications: { type: 'CP-II', standard: 'NBR 11578', weight: '1000kg' },
    unitPrice: 580,
    minimumOrderQuantity: 5,
    leadTime: 5,
    availability: 'in_stock',
  },
  {
    id: 14,
    name: 'Structural Steel Beam W200x15',
    description: 'Hot-rolled W200x15.0 structural steel beam, ASTM A572 Grade 50, 6m length.',
    price: 1240,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
    category: 'Construction',
    supplierId: 5,
    supplier: {
      id: 5,
      companyName: 'BuildPro Materials',
      corporateName: 'BuildPro Materials LTDA',
    },
    tierPricing: [],
    specifications: { profile: 'W200x15', length: '6m', grade: 'ASTM A572' },
    unitPrice: 1240,
    minimumOrderQuantity: 4,
    leadTime: 8,
    availability: 'in_stock',
  },
  {
    id: 15,
    name: 'Concrete Block 14x19x39 (pallet)',
    description: 'Structural concrete blocks 14x19x39cm, 4 MPa, supplied per pallet of 180 units.',
    price: 420,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
    category: 'Construction',
    supplierId: 5,
    supplier: {
      id: 5,
      companyName: 'BuildPro Materials',
      corporateName: 'BuildPro Materials LTDA',
    },
    tierPricing: [
      { minQuantity: 2, maxQuantity: 10, discount: 0 },
      { minQuantity: 11, maxQuantity: null, discount: 0.1 },
    ],
    specifications: { dimensions: '14x19x39cm', perPallet: '180', strength: '4 MPa' },
    unitPrice: 420,
    minimumOrderQuantity: 2,
    leadTime: 6,
    availability: 'in_stock',
  },
  {
    id: 16,
    name: 'Waterproofing Membrane Roll',
    description:
      'Asphaltic waterproofing membrane, 3mm thick, 10m2 per roll, polyester reinforced.',
    price: 315,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd',
    category: 'Construction',
    supplierId: 5,
    supplier: {
      id: 5,
      companyName: 'BuildPro Materials',
      corporateName: 'BuildPro Materials LTDA',
    },
    tierPricing: [],
    specifications: { area: '10m2', thickness: '3mm', type: 'Asphaltic' },
    unitPrice: 315,
    minimumOrderQuantity: 10,
    leadTime: 7,
    availability: 'limited',
  },
  {
    id: 17,
    name: 'Industrial Degreaser Concentrate 20L',
    description:
      'Biodegradable alkaline degreaser concentrate, 1:10 dilution, for heavy industrial cleaning.',
    price: 260,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    category: 'Chemicals',
    supplierId: 6,
    supplier: {
      id: 6,
      companyName: 'ChemSource Industrial',
      corporateName: 'ChemSource Industrial SA',
    },
    tierPricing: [
      { minQuantity: 4, maxQuantity: 20, discount: 0 },
      { minQuantity: 21, maxQuantity: null, discount: 0.09 },
    ],
    specifications: { volume: '20L', dilution: '1:10', biodegradable: 'Yes' },
    unitPrice: 260,
    minimumOrderQuantity: 4,
    leadTime: 5,
    availability: 'in_stock',
  },
  {
    id: 18,
    name: 'Epoxy Floor Coating Kit',
    description:
      'Two-component self-leveling epoxy floor coating, glossy finish, covers 25m2 per kit.',
    price: 690,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    category: 'Chemicals',
    supplierId: 6,
    supplier: {
      id: 6,
      companyName: 'ChemSource Industrial',
      corporateName: 'ChemSource Industrial SA',
    },
    tierPricing: [],
    specifications: { coverage: '25m2', components: '2', finish: 'Glossy' },
    unitPrice: 690,
    minimumOrderQuantity: 2,
    leadTime: 9,
    availability: 'in_stock',
  },
  {
    id: 19,
    name: 'Nitrile Safety Gloves (box of 100)',
    description: 'Powder-free nitrile examination gloves, EN 374 chemical resistance, box of 100.',
    price: 89,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    category: 'Safety',
    supplierId: 6,
    supplier: {
      id: 6,
      companyName: 'ChemSource Industrial',
      corporateName: 'ChemSource Industrial SA',
    },
    tierPricing: [
      { minQuantity: 20, maxQuantity: 200, discount: 0 },
      { minQuantity: 201, maxQuantity: null, discount: 0.18 },
    ],
    specifications: { size: 'M-L', standard: 'EN 374', count: '100' },
    unitPrice: 89,
    minimumOrderQuantity: 20,
    leadTime: 3,
    availability: 'in_stock',
  },
  {
    id: 20,
    name: 'Industrial Solvent Cleaner 50L',
    description: 'High-flash-point solvent cleaner for degreasing metal parts, 50L drum.',
    price: 540,
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    category: 'Chemicals',
    supplierId: 6,
    supplier: {
      id: 6,
      companyName: 'ChemSource Industrial',
      corporateName: 'ChemSource Industrial SA',
    },
    tierPricing: [],
    specifications: { volume: '50L', flashPoint: '62C', use: 'Degreasing' },
    unitPrice: 540,
    minimumOrderQuantity: 2,
    leadTime: 6,
    availability: 'custom_order',
  },
];
